config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  resources :variations
  resources :sizes
  resources :colors
  devise_for :users
  devise_for :admins
  root to: "home#index"

  authenticate :admin do
    resources :products
    resources :categories
  end

  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/variation.rb
class Variation < ApplicationRecord
  belongs_to :product
  belongs_to :color
  belongs_to :size

    validates :stock, presence: true
    validates :price, presence: true
    

end

app/controllers/variations_controller.rb
class VariationsController < ApplicationController
  before_action :set_variation, only: %i[ show edit update destroy ]

  # GET /variations or /variations.json
  def index
    @variations = Variation.all
  end

  # GET /variations/1 or /variations/1.json
  def show
  end

  # GET /variations/new
  def new
    @variation = Variation.new
  end

  # GET /variations/1/edit
  def edit
  end

  # POST /variations or /variations.json
  def create
    @variation = Variation.new(variation_params)

    respond_to do |format|
      if @variation.save
        format.html { redirect_to @variation, notice: "Variation was successfully created." }
        format.json { render :show, status: :created, location: @variation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variations/1 or /variations/1.json
  def update
    respond_to do |format|
      if @variation.update(variation_params)
        format.html { redirect_to @variation, notice: "Variation was successfully updated." }
        format.json { render :show, status: :ok, location: @variation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variations/1 or /variations/1.json
  def destroy
    @variation.destroy
    respond_to do |format|
      format.html { redirect_to variations_url, notice: "Variation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variation
      @variation = Variation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def variation_params
      params.require(:variation).permit(:price, :stock, :sku, :product_id, :color_id, :size_id)
    end
end

app/helpers/variations_helper.rb
module VariationsHelper
end

app/views/variations/_form.html.erb
<%= form_with(model: variation, local: true) do |form| %>
  <% if variation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variation.errors.count, "error") %> prohibited this variation from being saved:</h2>

      <ul>
      <% variation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :color_id %>
    <%= form.text_field :color_id %>
  </div>

  <div class="field">
    <%= form.label :size_id %>
    <%= form.text_field :size_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/variations/edit.html.erb
<h1>Editing Variation</h1>

<%= render 'form', variation: @variation %>

<%= link_to 'Show', @variation %> |
<%= link_to 'Back', variations_path %>

app/views/variations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variations</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Stock</th>
      <th>Sku</th>
      <th>Product</th>
      <th>Color</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variations.each do |variation| %>
      <tr>
        <td><%= variation.price %></td>
        <td><%= variation.stock %></td>
        <td><%= variation.sku %></td>
        <td><%= variation.product %></td>
        <td><%= variation.color %></td>
        <td><%= variation.size %></td>
        <td><%= link_to 'Show', variation %></td>
        <td><%= link_to 'Edit', edit_variation_path(variation) %></td>
        <td><%= link_to 'Destroy', variation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variation', new_variation_path %>

app/views/variations/new.html.erb
<h1>New Variation</h1>

<%= render 'form', variation: @variation %>

<%= link_to 'Back', variations_path %>

app/views/variations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @variation.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @variation.stock %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @variation.sku %>
</p>

<p>
  <strong>Product:</strong>
  <%= @variation.product %>
</p>

<p>
  <strong>Color:</strong>
  <%= @variation.color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @variation.size %>
</p>

<%= link_to 'Edit', edit_variation_path(@variation) %> |
<%= link_to 'Back', variations_path %>